server:
  port: ${PORT:22100}
spring:
  application:
    name: xc-service-base-filesystem
  #mongo配置
  data:
    mongodb:
      database: xc_fs
      uri: mongodb://root:root@127.0.0.1:27017
  #SpringMVC上传文件配置
  servlet:
    multipart:
      #默认支持文件上传.
      enabled: true
      #支持文件写入磁盘.
      file-size-threshold: 0
      # 上传文件的临时目录
      location:
      # 最大支持文件大小
      max-file-size: 5MB
      # 最大支持请求大小
      max-request-size: 30MB
fdfs:
  ## tracker地址 22122为默认端口
  trackerList: 47.98.149.200:22122
  ## 连接超时时间
  connect-timeout: 10000000
  ## 读取inputsream阻塞时间
  so-timeout: 300000000
  pool:
    ## 连接池最大数量
    max-total: 200
    ## 每个tracker地址的最大连接数
    max-total-per-key: 50
    ## 连接耗尽时等待获取连接的最大毫秒数
    max-wait-millis: 250000000

eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/}
  instance:
    prefer-ip-address:  true  #将自己的ip地址注册到Eureka服务中
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.application.name}:${server.port} #指定实例id
