server:
  port: ${PORT:31001}
spring:
  freemarker:
    cache: false
    settings:
      template_update_delay: 0
  application:
#    微服务名
    name: xc-service-manage-cms
  data:
    mongodb:
      uri:  mongodb://root:root@192.168.31.160:27017
      database: xc_cms
#      生产方配置mq
  rabbitmq:
    host: 47.98.149.200
    port: 5672
    username: admin
    password: admin
    virtual-host: my_vhost

eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/}
  instance:
    prefer-ip-address:  true  #将自己的ip地址注册到Eureka服务中
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.application.name}:${server.port} #指定实例id