server:
  port: 31000
spring:
  application:
    name: xc-service-manage-cms-client
  data:
    mongodb:
      uri:  mongodb://root:root@192.168.31.160:27017
      database: xc_cms
# 阿里云中间件
  rabbitmq:
    host: 47.98.149.200
    port: 5672
    username: admin
    password: admin
    virtualHost: my_vhost

#rabbitmq配置信息从这里加载
xuecheng:
  mq:
    #cms客户端监控的队列名称（不同的客户端监控的队列不能重复）
    queue: queue_cms_postpage_01
    routingKey: 5a751fab6abb5044e0d19ea1    #此routingKey为门户站点ID
