server:
  port: 31450
spring:
  application:
    name: xc-service-manage-media-processor
  data:
    mongodb:
      uri:  mongodb://root:root@localhost:27017
      database: xc_media
#rabbitmq配置
  rabbitmq:
    host: 47.98.149.200
    port: 5672
    username: admin
    password: admin
    virtual-host: my_vhost
xc-service-manage-media:
  mq:
    queue-media-video-processor: queue_media_video_processor
    routingkey-media-video: routingkey_media_video
  video-location: D:/Development/xuechengzaixian/video/
  ffmpeg-path: D:/ffmpeg/bin/ffmpeg.exe